accession-list: data/SRA_accession_list.test.2.txt
ref-genome:     data/Danio_rerio.GRCz11.dna_sm.primary_assembly.fa
ref-genome-gtf: data/Danio_rerio.GRCz11.108.gtf
ercc-fa:  data/ERCC92.fa
ercc-gtf: data/ERCC92.gtf
genome-size: 1396431182
#hisat-ref-indexes:     Danio_rerio_genome
star-ref-indexes-ercc: star_Danio_rerio_indexes.ERCC
star-ref-indexes:      star_Danio_rerio_indexes
bowtie-ref-indexes:    bowtie2_index
gsnap-ref-indexes:    gmap_Danio_rerio_index
hisat-use-transcript: true
publish-intermediate: true
star-use-shared-mem: false
skip-host-counts: true
max-cpus: 4
